
version: 1.0.{build}
configuration: Debug
platform: x64
image:
  - macos
  - Visual Studio 2019
  - Visual Studio 2015

for:
  -
    matrix:
      only:
        - image: macos

    build_script:
      - mkdir build_imebra_release
      - mkdir build_imebra_ios_release
      - cd build_imebra_release
      - cmake --config Release ..
      - cmake --build . --config Release
      - ctest -V .
      - cd ../build_imebra_ios_release
      - cmake --config Release -DIOS=IPHONE ..
      - cmake --build . --config Release
      - cd ..
      - cp -R library/include build_imebra_release
      - cp -R library/include build_imebra_ios_release

    artifacts:
      - path: build_imebra_release/*.dylib
        name: imebra_macos_release
      - path: build_imebra_ios_release/*.a
        name: imebra_ios_release

  -
    matrix:
      only:
        - image: Visual Studio 2015

    build_script:
      - cmd: >-

          mkdir build_imebra_release

          mkdir build_imebra_debug

          cd build_imebra_release
    
          cmake --config Release ..
    
          cmake --build . --config Release

          ctest -V .

          cd ..

          mkdir build_imebra_release\Release\include
    
          mkdir build_imebra_debug\Debug\include

          xcopy library\include build_imebra_release\Release\include /s /e

          xcopy library\include build_imebra_debug\Debug\include /s /e

    artifacts:
      - path: build_imebra_release/Release
        name: imebra_release

build_script:
- cmd: >-

    mkdir build_imebra_release

    mkdir build_imebra_debug

    cd build_imebra_release
    
    cmake --config Release ..
    
    cmake --build . --config Release

    ctest -V .

    cd ../build_imebra_debug
    
    cmake --config Debug ..
    
    cmake --build . --config Debug

    cd ..

    mkdir build_imebra_release\Release\include
    
    mkdir build_imebra_debug\Debug\include

    xcopy library\include build_imebra_release\Release\include /s /e

    xcopy library\include build_imebra_debug\Debug\include /s /e

test_script:
- cmd: 
artifacts:
- path: build_imebra_release/Release
  name: imebra_windowsrelease
- path: build_imebra_debug/Debug
  name: imebra_debug
