
version: 1.0.{build}
configuration: Debug
platform: x64
image:
  - macos
  - Visual Studio 2019
  - Visual Studio 2015

for:
  -
    matrix:
      only:
        - image: macos

    build_script:
      - mkdir build_imebra_debug
      - mkdir build_imebra_ios_debug
      - cd build_imebra_debug
      - cmake -DCMAKE_BUILD_TYPE=Debug ..
      - cmake --build . --config Debug
      - ctest -V .
      - cd ../build_imebra_ios_debug
      - cmake -DCMAKE_BUILD_TYPE=Debug -DIOS=IPHONE ..
      - cmake --build . --config Debug
      - cd ..
      - cp -R library/include build_imebra_debug
      - cp -R library/include build_imebra_ios_debug

    artifacts:
      - path: build_imebra_debug/*.dylib
        name: imebra_macos_debug
      - path: build_imebra_ios_debug/*.a
        name: imebra_ios_debug

  -
    matrix:
      only:
        - image: Visual Studio 2015

    build_script:
      - cmd: >-

          mkdir build_imebra_release

          cd build_imebra_release
    
          cmake -DCMAKE_BUILD_TYPE=Release ..
    
          cmake --build . --config Release

          ctest -V .

          cd ..

          mkdir build_imebra_release\Release\include
    
          mkdir build_imebra_debug\Debug\include

          xcopy library\include build_imebra_release\Release\include /s /e

          xcopy library\include build_imebra_debug\Debug\include /s /e

    artifacts:
      - path: build_imebra_release/Release
        name: imebra__vs2015_release

build_script:
- cmd: >-

    mkdir build_imebra_release

    mkdir build_imebra_debug

    cd build_imebra_release
    
    cmake -DCMAKE_BUILD_TYPE=Release ..
    
    cmake --build . --config Release

    ctest -V .

    cd ../build_imebra_debug
    
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    
    cmake --build . --config Debug

    cd ..

    mkdir build_imebra_release\Release\include
    
    mkdir build_imebra_debug\Debug\include

    xcopy library\include build_imebra_release\Release\include /s /e

    xcopy library\include build_imebra_debug\Debug\include /s /e

test_script:
- cmd: 
artifacts:
- path: build_imebra_release/Release
  name: imebra_vs2019_release
- path: build_imebra_debug/Debug
  name: imebra_vs2019_debug
