
version: 1.0.{build}
configuration: Debug
platform: x64
image:
  - Visual Studio 2019
  - Visual Studio 2015

build_script:
- cmd: >-

    mkdir build_imebra_release

    mkdir build_imebra_debug

    cd build_imebra_release
    
    cmake --config Release ..
    
    cmake --build . --config Release

    ctest -V .

    cd ../build_imebra_debug
    
    cmake --config Debug ..
    
    cmake --build . --config Debug

    cd ..

    mkdir build_imebra_release\Release\include
    
    mkdir build_imebra_debug\Debug\include

    xcopy library\include build_imebra_release\Release\include /s /e

    xcopy library\include build_imebra_debug\Debug\include /s /e

test_script:
- cmd: 
artifacts:
- path: build_imebra_release/Release
  name: imebra_release
- path: build_imebra_debug/Debug
  name: imebra_debug
